baseURL = 'https://riogu.github.io/'
languageCode = 'en-us'
title = 'Egas Ribeiro'
theme = 'PaperMod'
enableRobotsTXT = true
enableEmoji = true
pygmentsUseClasses = true

[pagination]
  pagerSize = 10

[params]
  env = 'production'
  description = 'Write-ups on compilers, static analysis, and my work on GCC.'
  defaultTheme = 'auto'
  ShowReadingTime = false
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = false
  ShowRssButtonInSectionTermList = false
  ShowToc = true
  capitalizeListTitles = false
  TocOpen = false
  disableSpecial1stPost = false
  hidemeta = false
  comments = false
  hideFooter = true

  [params.homeInfoParams]
    Title = "Egas"
    Content = """
GCC contributor, I usually work on the C++ frontend or the Static Analyzer when I have the time.\\
I'm starting the PhD prep phase (MSc) at the Saarbrücken Graduate
School of Computer Science this October to do compiler-related research.

Here there will mostly be posts on compiler related work or whatever I'm currently working on.\\
See my [GSoC 2026 write-up](/posts/gsoc-2026/) or the [posts](/posts/) list.
"""

[markup]
  [markup.highlight]
    noClasses = false
    codeFences = true
    guessSyntax = false
    lineNos = false
  [markup.goldmark.renderer]
    unsafe = true

[[menu.main]]
  identifier = 'posts'
  name = 'Posts'
  url = '/posts/'
  weight = 10

[[menu.main]]
  identifier = 'about'
  name = 'About'
  url = '/about/'
  weight = 20

[[menu.main]]
  identifier = 'github'
  name = 'GitHub'
  url = 'https://github.com/riogu'
  weight = 30 

[outputs]
  home = ['HTML', 'RSS', 'JSON']
